### ISSUE TITLE
Deprecated syntax

### ISSUE THREAD

**Issue by webstandardcss** [ANXS/utilities#7]
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks
 so that the environment value uses the full variable syntax
('{{utilities_base}}').
This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.

**Comment by otakup0pe** [comment]
Fixed in https://github.com/ANXS/utilities/tree/v1.0.6
